/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4QUG7D9huwm
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/app/components/ui/card"

export function Discography() {
  return (
    <main className="flex flex-col items-center justify-center p-4 md:p-6">
      <h1 className="text-4xl font-bold mb-2">Discography</h1>
      <div className="flex justify-center space-x-4 mb-6">
        <div className="h-6 w-6 text-red-600" />
        <div className="h-6 w-6 text-green-600" />
      </div>
      <section className="grid grid-cols-1 gap-4 md:gap-6 xl:gap-8">
        <Card className="w-lg max-w-xl p-6 grid gap-0">
          <CardHeader className="grid gap-1 text-center space-y-0 p-0">
            <CardTitle className="text-lg">Album Title</CardTitle>
            <CardDescription className="text-xs">1st full album - Feb. 25, 2024</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row items-center gap-8 justify-center mt-4">
            <img
              alt="Album Cover"
              className="object-cover"
              height={240}
              src="/placeholder.svg"
              style={{
                aspectRatio: "240/240",
                objectFit: "cover",
              }}
              width={240}
            />
            <div className="p-0 grid gap-2">
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">1. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">2. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">3. おはよう</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">4. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">5. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">6. こんにちは</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">7. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">8. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">9. こんばんは</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">10. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">11. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">12. おはよう、こんにちは、こんばんは</div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="text-sm mt-4">
            Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis libero in justo
            ultricies, in dignissim ex ultricies.
          </CardFooter>
        </Card>
        <Card className="w-lg max-w-xl p-6 grid gap-0">
          <CardHeader className="grid gap-1 text-center space-y-0 p-0">
            <CardTitle className="text-lg">Single Title</CardTitle>
            <CardDescription className="text-xs">Digital release - Jan. 12, 2024</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row items-center gap-8 justify-center mt-4">
            <img
              alt="Album Cover"
              className="object-cover"
              height={240}
              src="/placeholder.svg"
              style={{
                aspectRatio: "240/240",
                objectFit: "cover",
              }}
              width={240}
            />
            <div className="p-0 grid gap-2">
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">1. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">2. Song Title</div>
              </div>
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">3. おはよう</div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="text-sm mt-4">
            Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis libero in justo
            ultricies, in dignissim ex ultricies.
          </CardFooter>
        </Card>
        <Card className="w-lg max-w-xl p-6 grid gap-0">
          <CardHeader className="grid gap-1 text-center space-y-0 p-0">
            <CardTitle className="text-lg">Single Title</CardTitle>
            <CardDescription className="text-xs">Single - Sep. 5, 2023</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col md:flex-row items-center gap-8 justify-center mt-4">
            <img
              alt="Album Cover"
              className="object-cover"
              height={240}
              src="/placeholder.svg"
              style={{
                aspectRatio: "240/240",
                objectFit: "cover",
              }}
              width={240}
            />
            <div className="p-0 grid gap-2">
              <div className="flex items-center gap-2 text-sm">
                <div className="flex gap-2 items-center">1. Song Title</div>
              </div>
            </div>
          </CardContent>
          <CardFooter className="text-sm mt-4">
            Description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla convallis libero in justo
            ultricies, in dignissim ex ultricies.
          </CardFooter>
        </Card>
      </section>
    </main>
  )
}
